# Generated by Django 3.2.13 on 2022-05-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exame', models.CharField(max_length=100)),
                ('Jejum', models.CharField(choices=[('4HORAS', '4 Horas'), ('6HORAS', '6 Horas'), ('8HORAS', '8 Horas'), ('12HORAS', '12 Horas'), ('NÃO_NECESSARIO', 'Não é necessário')], max_length=25)),
                ('Material', models.CharField(choices=[('SORO', 'Soro'), ('EDTA', 'Sangue Total'), ('EDTAPLASMA', 'Plasma EDTA'), ('CITRATO', 'Plasma Citrato'), ('HEPARINA', 'Heparina'), ('TRACE', 'Tubo Trace')], max_length=25)),
                ('Prazo', models.CharField(max_length=15)),
                ('Ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
            },
        ),
    ]
