# Generated by Django 3.2.13 on 2022-05-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exame',
            old_name='Exame',
            new_name='Nome',
        ),
    ]
